name: CI
on:
    push:

jobs:
    main:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v2.4.0
              with:
                  version: latest
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
                  cache: "pnpm"

            - name: Build
              run: |
                  pnpm install
                  pnpm run build
                  pnpm run export
